apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-platform-prod
  namespace: prod
  labels:
    app: devops-platform
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-platform
  template:
    metadata:
      labels:
        app: devops-platform
        env: prod
    spec:
      containers:
      - name: devops-platform
        image: nadineibrahim/devops-platform:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
