apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-platform-dev
  namespace: dev
  labels:
    app: devops-platform
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-platform
  template:
    metadata:
      labels:
        app: devops-platform
        env: dev
    spec:
      containers:
      - name: devops-platform
        image: nadineibrahim/devops-platform:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
