apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-platform
  labels:
    app: devops-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-platform
  template:
    metadata:
      labels:
        app: devops-platform
    spec:
      containers:
      - name: devops-platform
        image: nadineibrahim/devops-platform:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
